site_name: Marketing Docs
repo_url: https://github.com/LACMTA/marketing-docs/

theme:
  palette:

    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  font:
    text: Open Sans
  favicon: assets/media/favicon.png
  logo: assets/media/favicon-reverse.png
  name: material
  # custom_dir: overrides
  features:
      - navigation.instant
      - navigation.tabs
      - content.code.annotate
      - search.highlight
      - toc.integrate
      - navigation.indexes
      - navigation.top
      - search.suggest      

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
    #     linenums: true
    - pymdownx.superfences
    - pymdownx.magiclink
    - smarty
    - meta
    - toc:
        permalink: True
        toc_depth: 2
    - sane_lists
    - admonition
    - footnotes
    - attr_list
    
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - ../assets/javascripts/tables.js
  - ../assets/javascripts/extra.js
extra_css:
  - ../assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/metrolosangeles

edit_uri: edit/dev/docs/
plugins:
  - search:
      lang: en
      # prebuild_index: true
  - git-revision-date
  - autorefs
  - table-reader
  - macros
  - tags
  - awesome-pages
        # tags_file: /assets/tags/tags.md

  # - htmlproofer
      # raise_error: True
  # - encryptcontent:
  #     title_prefix: '🔒'
  #     # global_password: !ENV METRO_DOCS_PASS
  #     # password_button: True      
  #     encrypted_something:
  #         mkdocs-encrypted-toc: [nav, class]
  #         mkdocs-encrypted-footer: [div, id]
  #         mkdocs-encrypted-footer-meta: [div, id]