backend:
  name: github
  repo: lacmta/marketing-docs
  branch: dev
  api_root: https://api.github.com 
  base_url: https://metro-oauth-login.herokuapp.com/
  auth_endpoint: auth
  preview_context: github/deployment

logo_url: https://i0.wp.com/brand.metro.net/wp-content/uploads/2018/07/MetroLogo_SpecialConditions5.jpg?fit=72%2C72&ssl=1
public_folder: "site"
media_folder: "site/assets"

collections: # A list of collections the CMS should be able to edit
  - name: 'processes' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Processes' # Used in the UI
    label_singular: 'Process' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'docs/_Processes'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''

      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: 'resources' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Resources' # Used in the UI
    label_singular: 'Resource' # Used in the UI, ie: "New Post"
    description: >
      A resource is something that people at Metro use.
    folder: 'docs/_Resources'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''

      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
