# Page structure
# 1. Title
# 2. Last updated
# 3. Author
# 4. Who is this content for?
      # -Drop-down?? TBD
# 5. How would they use this content? Why is it important?
# 6. Tags*
# 7. Content

# Tasks for today 2/3:
# 1. configure config.yml for the backend
# categories as selections

# 2. re-organize files based on new structure

# 3. re-pop old content

# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: github
  repo: lacmta/marketing-docs
  branch: dev
  api_root: https://api.github.com 
  base_url: https://metro-oauth-login.herokuapp.com/
  auth_endpoint: auth
  preview_context: github/deployment

logo_url: https://i0.wp.com/brand.metro.net/wp-content/uploads/2018/07/MetroLogo_SpecialConditions5.jpg?fit=72%2C72&ssl=1
public_folder: "site"
media_folder: "site/assets"

publish_mode: editorial_workflow


collections: # A list of collections the CMS should be able to edit
  - name: 'research-design' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Research Design' # Used in the UI
    label_singular: 'Research Design' # Used in the UI, ie: "New Post"
    description: >
      R&D! WE COOL! To help inform updates and new projects.
    folder: 'docs/Research-Design'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } } 
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Audience', name: 'audience', widget: 'select', hint: 'Who is this content for?', options: ['Contractors', 'New Hires', 'Marketing', 'Design', 'Digital', 'Managers'], multiple: true}
      - { label: 'Purpose', name: 'purpose', widget: 'string', hint: 'How would this content be used? Why is it important?' }
      - { label: 'Tags', name: 'tags', widget: 'list', summary: '{{fields.name}}', field: {label: 'Name', name: 'name', widget: 'string'}}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
    
    
  - name: 'support' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Support' # Used in the UI
    label_singular: 'Support' # Used in the UI, ie: "New Post"
    description: >
      We support you! :)
    folder: 'docs/Support'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Audience', name: 'audience', widget: 'select', hint: 'Who is this content for?', options: ['Contractors', 'New Hires', 'Marketing', 'Design', 'Digital', 'Managers'], multiple: true}
      - { label: 'Purpose', name: 'purpose', widget: 'string', hint: 'How would this content be used? Why is it important?' }
      - { label: 'Tags', name: 'tags', widget: 'list', summary: '{{fields.name}}', field: {label: 'Name', name: 'name', widget: 'string'}}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  - name: 'marketing-resources' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Marketing Resources' # Used in the UI
    label_singular: 'Marketing Resource' # Used in the UI, ie: "New Post"
    description: >
      Marketing resources! Description goes here.
    folder: 'docs/Marketing-Resources'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Audience', name: 'audience', widget: 'select', hint: 'Who is this content for?', options: ['Contractors', 'New Hires', 'Marketing', 'Design', 'Digital', 'Managers'], multiple: true}
      - { label: 'Purpose', name: 'purpose', widget: 'string', hint: 'How would this content be used? Why is it important?' }
      - { label: 'Tags', name: 'tags', widget: 'list', summary: '{{fields.name}}', field: {label: 'Name', name: 'name', widget: 'string'}}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      
  - name: 'getting-started' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Getting Started' # Used in the UI
    label_singular: 'Getting Started post' # Used in the UI, ie: "New Post"
    description: >
      Documentation and links that would be helpful for new hires or new contractors.
    folder: 'docs/Getting-Started'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Author', name: 'author', widget: 'string',  default: {{field.author}}}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Audience', name: 'audience', widget: 'select', hint: 'Who is this content for?', options: ['Contractors', 'New Hires', 'Marketing', 'Design', 'Digital', 'Managers'], multiple: true}
      - { label: 'Purpose', name: 'purpose', widget: 'string', hint: 'How would this content be used? Why is it important?' }
      - { label: 'Tags', name: 'tags', widget: 'list', summary: '{{fields.name}}', field: {label: 'Name', name: 'name', widget: 'string'}}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  - name: 'developer-docs'
    label: 'Developer Docs'
    label_singular: 'Developer Docs post'
    description: >
      Documentation relevant for digital services development projects.
    folder: 'docs/Developer-Docs'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Author', name: 'author', widget: 'string',  default: {{field.author}}}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Audience', name: 'audience', widget: 'select', hint: 'Who is this content for?', options: ['Contractors', 'New Hires', 'Marketing', 'Design', 'Digital', 'Managers'], multiple: true}
      - { label: 'Purpose', name: 'purpose', widget: 'string', hint: 'How would this content be used? Why is it important?' }
      - { label: 'Tags', name: 'tags', widget: 'list', summary: '{{fields.name}}', field: {label: 'Name', name: 'name', widget: 'string'}}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
