name: ci 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://github.com/LACMTA/mkdocs-material-insiders.git
      - run: pip install mkdocs-encryptcontent-plugin
      # - run: pip install pip install --upgrade mkdocs-material
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-autorefs
      - run: pip install mkdocs-macros-plugin     
      - run: pip install mkdocs-table-reader-plugin   
      - run: mkdocs gh-deploy --force
      # - run: pip install mkdocs-material
env:
  GH_TOKEN: ${{secrets.ALBERT_KEY}}          
  METRO_DOCS_PASS: ${{secrets.METRO_DOCS_PASS}}

