# This is a basic workflow to help you get started with Actions

name: pull from dev to main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        TARGET_BRANCH: 'main'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout $TARGET_BRANCH       
          git checkout ${GITHUB_REF##*/} -- $files
          git add .
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH # push to remote branch