# This is a basic workflow to help you get started with Actions

name: pull from dev to main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  nightly-merge:

    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout main
          git merge dev
          git add .
          git commit -am "deploy files"
          git push origin main
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # - run: pip install git+https://${GH_TOKEN}@github.com/LACMTA/mkdocs-material-insiders.git
      - run: git clone --depth 1 https://${GH_TOKEN}@github.com/LACMTA/mkdocs-material-insiders.git
      - run: pip install -e mkdocs-material-insiders
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-encryptcontent-plugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-autorefs
      - run: pip install mkdocs-table-reader-plugin   
      - run: pip install mkdocs-awesome-pages-plugin
      # - run: pip install jinja2==3.0.0
      # - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{secrets.ALBERT_KEY}}          
  METRO_DOCS_PASS: ${{secrets.METRO_DOCS_PASS}}

