# This is a basic workflow to help you get started with Actions

name: pull from dev to main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: git config --global --add safe.directory /github/workspace
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.2
      with:
        stable_branch: 'dev'
        development_branch: 'main'
        allow_ff: false
        allow_forks: true
      env:
        GITHUB_TOKEN: ${{ secrets.METRO_KEY }}
